name: Update README

on:
  push:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Install markscribe CLI
        run: |
          curl -sSL -o /usr/local/bin/markscribe https://github.com/charmbracelet/markscribe/releases/download/v0.7.0/markscribe-linux-amd64
          chmod +x /usr/local/bin/markscribe

      - name: Generate README.md with markscribe
        run: markscribe --template templates/README.md.tpl --out README.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated README
          branch: main
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>
